video-iter:
	ffmpeg -i video-iter.flv -c:v libx264 -crf 19 -strict experimental -ss 3 -to 96 -an video-iter.mp4
video-canvas:
	ffmpeg -i video-canvas.flv -c:v libx264 -crf 19 -strict experimental -ss 3 -to 36 -an video-canvas.mp4
video-flow:
	ffmpeg -i video-flow.flv -c:v libx264 -crf 19 -strict experimental -ss 3 -to 36 -an video-flow.mp4
